config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  resources :rooms
  resources :studios
  resources :studios do
    member do
      get 'studio_image'
    end
  end
  resources :accounts
  namespace :admin do
    root 'top#index'
    resources :studios do
      get :upload
      resources :studio_images do
        collection do
          post :upload
        end
      end
    end
    resources :rooms
    resources :areas
  end
  get '*unmatched_route', to: redirect('/'), format: false unless Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/studio_image.rb
class StudioImage < ApplicationRecord
  mount_uploader :url, StudioImageUploader

  belongs_to :studio, optional: true
end

app/controllers/admin/studio_images_controller.rb
# frozen_string_literal: true
module Admin
  class StudioImagesController < Admin::ApplicationController
    def  upload
      @studio = Studio.friendly.find(params[:studio_id])
      studio_image = @studio.studio_images.build(url: params['file'], studio_id: @studio.id)
      studio_image.save
    end
  end
end

app/views/admin/studio_images/_form.html.erb
<%= form_tag(upload_admin_studio_studio_images_path(@studio), id: 'studio-image-dropzone', class: 'dropzone', method: :post) %>

<script type="text/javascript">
  Dropzone.autoDiscover = false;

  Dropzone.options.studioImageDropzone = {
    paramName: "file",         // input fileの名前
    parallelUploads: 10,            // 1度に何ファイルずつアップロードするか
    acceptedFiles: 'image/*',   // 画像だけアップロードしたい場合
    maxFiles: 10,                      // 1度にアップロード出来るファイルの数
    maxFilesize: 100,                // 1つのファイルの最大サイズ(1=1M)
    dictFileTooBig: "ファイルが大きすぎます。 ({{filesize}}MiB). 最大サイズ: {{maxFilesize}}MiB.",
    dictInvalidFileType: "画像ファイル以外です。",
    dictMaxFilesExceeded: "一度にアップロード出来るのは10ファイルまでです。",
    dictDefaultMessage: 'アップロードする画像をここにドラッグ&ドロップしてください。'
  };
  var studioImageDropzone = new Dropzone("#studio-image-dropzone");
</script>

app/views/admin/studio_images/edit.html.erb
<h1>Editing Studio</h1>

<p><%= link_to "#{@studio.name}のroom編集へ", admin_rooms_path(studio_id: @studio.id) %></p>

<%= render 'form', studio: @studio %>

<p><%= link_to "#{@studio.name}のroom編集へ", admin_rooms_path(studio_id: @studio.id) %></p>

<%= link_to 'Show', @studio, class: 'btn previous' %> |
<%= link_to 'Back', admin_studios_path, class: 'btn' %>

app/views/admin/studio_images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Studios</h1>

<%= link_to 'New Studio', new_admin_studio_path %>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>スタジオ名</th>
      <th>エリア</th>
      <th>住所</th>
      <th>最寄り駅</th>
      <th>電話番号</th>
      <th>営業時間</th>
      <th>状態</th>
      <th>メモ</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @studios.each do |studio| %>
      <tr>
        <td><%= studio.id %></td>
        <td><%= studio.name %></td>
        <td><%= studio.area.city %></td>
        <td><%= studio.address %></td>
        <td><%= "#{studio.nearest_station_1}, #{studio.nearest_station_2}, #{studio.nearest_station_3}" %></td>
        <td><%= studio.tel %></td>
        <td><%= "#{studio.start_hours&.strftime("%H:%M")} - #{studio.end_hours&.strftime("%H:%M")}" %></td>
        <td><%= studio.status %></td>
        <td><%= studio.memo %></td>
        <!--
        <td><%= link_to 'Show', admin_studio_path(studio) %></td>
        -->
        <td><%= link_to 'Edit', edit_admin_studio_path(studio) %></td>
        <td><%= link_to 'Destroy', admin_studio_path(studio), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Studio', new_admin_studio_path %>

app/views/admin/studio_images/new.html.erb
<h1>New Studio</h1>

<%= render 'form', studio: @studio %>

<%= link_to 'Back', admin_studios_path %>