config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  resources :rooms
  resources :studios
  resources :studios do
    member do
      get 'studio_image'
    end
  end
  resources :accounts
  namespace :admin do
    root 'top#index'
    resources :studios do
      get :upload
      resources :studio_images do
        collection do
          post :upload
        end
      end
    end
    resources :rooms
    resources :areas
  end
  get '*unmatched_route', to: redirect('/'), format: false unless Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/area.rb
# frozen_string_literal: true
class Area < ApplicationRecord
  has_many :studios
end

app/controllers/admin/areas_controller.rb
# frozen_string_literal: true
module Admin
  class AreasController < Admin::ApplicationController
    layout 'admin'
    before_action :set_area, only: [:show, :edit, :update, :destroy]

    # GET /admin/areas
    # GET /admin/areas.json
    def index
      @areas = Area.all
    end

    # GET /admin/areas/1
    # GET /admin/areas/1.json
    def show
    end

    # GET /admin/areas/new
    def new
      @area = Area.new
    end

    # GET /admin/areas/1/edit
    def edit
    end

    # POST /admin/areas
    # POST /admin/areas.json
    def create
      @area = Area.new(area_params)

      respond_to do |format|
        if @area.save
          format.html { redirect_to admin_areas_path, notice: 'Area was successfully created.' }
          format.json { render :show, status: :created, location: @area }
        else
          format.html { render :new }
          format.json { render json: @area.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin/areas/1
    # PATCH/PUT /admin/areas/1.json
    def update
      respond_to do |format|
        if @area.update(area_params)
          format.html { redirect_to admin_areas_path, notice: 'Area was successfully updated.' }
          format.json { render :show, status: :ok, location: @area }
        else
          format.html { render :edit }
          format.json { render json: @area.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admin/areas/1
    # DELETE /admin/areas/1.json
    def destroy
      @area.destroy
      respond_to do |format|
        format.html { redirect_to admin_areas_path, notice: 'Area was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:prefecture, :city)
    end
  end
end

app/views/admin/areas/_form.html.erb
<%= form_for([:admin, area]) do |f| %>
  <% if area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label '都道府県', class: 'control-label' %>
    <%= f.text_field :prefecture, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label '市区町村', class: 'control-label' %>
    <%= f.text_field :city, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/areas/edit.html.erb
<h1>Editing Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Back', admin_areas_path, class: 'btn' %>

app/views/admin/areas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Areas</h1>

<%= link_to 'New Area', new_admin_area_path %>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>都道府県</th>
      <th>市区町村</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= area.id %></td>
        <td><%= area.prefecture %><td>
        <td><%= area.city %><td>
        <!--
        <td><%= link_to 'Show', admin_area_path(area) %></td>
        -->
        <td><%= link_to 'Edit', edit_admin_area_path(area) %></td>
        <td><%= link_to 'Destroy', admin_area_path(area), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Area', new_admin_area_path %>

app/views/admin/areas/new.html.erb
<h1>New Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Back', admin_areas_path %>

app/views/admin/areas/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_area_path(@admin_area) %> |
<%= link_to 'Back', admin_areas_path %>