config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  resources :rooms
  resources :studios
  resources :studios do
    member do
      get 'studio_image'
    end
  end
  resources :accounts
  namespace :admin do
    root 'top#index'
    resources :studios do
      get :upload
      resources :studio_images do
        collection do
          post :upload
        end
      end
    end
    resources :rooms
    resources :areas
  end
  get '*unmatched_route', to: redirect('/'), format: false unless Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/studio.rb
# frozen_string_literal: true
class Studio < ApplicationRecord
  include FriendlyId
  friendly_id :slug

  belongs_to :area
  has_many :studio_images
  has_many :rooms
  accepts_nested_attributes_for :studio_images

  scope :displayed, -> { where(status: Studio.statuses[:active]) }
  scope :by_area, ->(area) { where(area_id: Area.find_by(slug: area).id) if area.present? && area != 'all' }
  scope :by_people, ->(people) {
    return all unless people.present?
    people_range = PeopleRange.find(people)
    Studio.includes(:rooms).where(rooms: {capacity: people_range.min..people_range.max})
  }
  scope :by_late_night, ->(late_night) { where(late_night: late_night) if late_night.present? }
  scope :by_locker_room, ->(locker_room) { where(locker_room: locker_room) if locker_room.present? }
  scope :by_parking, ->(parking) { where(parking: parking) if parking.present? }
  scope :order_by_room_count, lambda {
    ids = joins(:rooms).group(:id).order('count_studios_id desc').count('studios.id').keys
    Studio.where(id: ids).order(['field(id, ?)', ids])
  }

  enum status: { inactive: 0, active: 1 }
  validates :slug, uniqueness: true

  def max_capacity
    rooms.maximum(:capacity)
  end

  def min_capacity
    rooms.minimum(:capacity)
  end
end

app/controllers/admin/studios_controller.rb
# frozen_string_literal: true
module Admin
  class StudiosController < Admin::ApplicationController
    layout 'admin'
    before_action :set_studio, only: [:show, :edit, :update, :destroy]

    # GET /studios
    # GET /studios.json
    def index
      @studios = Studio.page(params[:page]).per(1000)
    end

    # GET /studios/1
    # GET /studios/1.json
    def show
    end

    # GET /studios/new
    def new
      @studio = Studio.new
      @studio.studio_images.build
    end

    # GET /studios/1/edit
    def edit
      set_studio
      @studio.studio_images.build unless @studio.studio_images.present?
    end

    # POST /studios
    # POST /studios.json
    def create # rubocop:disable Metrics/AbcSize
      @studio = Studio.new(studio_params)

      respond_to do |format|
        if @studio.save
          format.html { redirect_to admin_studios_path, notice: 'Studio was successfully created.' }
          format.json { render :index }
        else
          format.html { render :new }
          format.json { render json: @studio.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /studios/1
    # PATCH/PUT /studios/1.json
    def update # rubocop:disable Metrics/AbcSize
      respond_to do |format|
        if @studio.update(studio_params)
          format.html { redirect_to admin_studios_path, notice: 'Studio was successfully updated.' }
          format.json { render :show, status: :ok, location: @studio }
        else
          format.html { render :edit }
          format.json { render json: @studio.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /studios/1
    # DELETE /studios/1.json
    def destroy
      @studio.destroy
      respond_to do |format|
        format.html { redirect_to admin_studios_path, notice: 'Studio was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    def upload
      @studio = Studio.friendly.find(params[:studio_id])
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_studio
      @studio = Studio.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def studio_params
      params.require(:studio).permit(:name, :area_id, :address, :nearest_station_1,
                                     :nearest_station_2, :nearest_station_3, :tel, :start_hours,
                                     :end_hours, :late_night, :locker_room, :parking,
                                     :cancell_deadline, :url, :feature, :remarks, :memo, :status,
                                     :slug, :meta_title, :meta_description, :meta_ogp_image_url,
                                     studio_images_attributes: [:id, :studio_id, :url])
    end
  end
end

app/controllers/studios_controller.rb
# frozen_string_literal: true
class StudiosController < ApplicationController
  layout :select_layout
  before_action :set_studio, only: [:show, :edit, :update, :destroy]
  before_action :url_formatter, only: :index

  # GET /studios
  # GET /studios.json
  def index # rubocop:disable Metrics/AbcSize
    @studios = Studio.displayed.by_late_night(params[:late_night]&.to_i).by_locker_room(params[:locker_room])
                     .by_parking(params[:parking]).by_area(session[:area]).by_people(session[:people])
                     .page(params[:page])
    @area = params[:area] == 'all' ? '首都圏' : Area.find_by(slug: session[:area]).city
    @people = session[:people].blank? || session[:people] == '6' ? '' : "#{PeopleRange.find(session[:people]).name}で使える"
  end

  # GET /studios/1
  # GET /studios/1.json
  def show
    @recommend_studios = Studio.displayed.by_area(session[:area]).by_people(session[:people]).where.not(id: @studio.id).limit(3)
  end

  # GET /studios/new
  def new
    @studio = Studio.new
  end

  # GET /studios/1/edit
  def edit
  end

  # POST /studios
  # POST /studios.json
  def create
    @studio = Studio.new(studio_params)

    respond_to do |format|
      if @studio.save
        format.html { redirect_to @studio, notice: 'Studio was successfully created.' }
        format.json { render :show, status: :created, location: @studio }
      else
        format.html { render :new }
        format.json { render json: @studio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studios/1
  # PATCH/PUT /studios/1.json
  def update
    respond_to do |format|
      if @studio.update(studio_params)
        format.html { redirect_to @studio, notice: 'Studio was successfully updated.' }
        format.json { render :show, status: :ok, location: @studio }
      else
        format.html { render :edit }
        format.json { render json: @studio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studios/1
  # DELETE /studios/1.json
  def destroy
    @studio.destroy
    respond_to do |format|
      format.html { redirect_to studios_url, notice: 'Studio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_studio
    @studio = Studio.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def studio_params
    params.require(:studio).permit(:name, :prefecture, :city, :address, :nearest_station_1,
                                   :nearest_station_2, :nearest_station_3, :tel, :start_hours,
                                   :end_hours, :late_night, :locker_room, :parking,
                                   :cancell_deadline, :image, :url, :feature, :remarks)
  end

  def select_layout
    if action_name == 'index'
      'studio_index'
    elsif action_name == 'show'
      'studio'
    end
  end

  def url_formatter
    return unless params[:button]
    area = case
           when session[:area].blank? && params[:area].blank?
             'all'
           when session[:area].present? && params[:area].blank?
             session[:area]
           else
             params[:area]
           end
    redirect_to studios_path(area: area, people: view_context.people_range_format(session[:people]))
  end
end

app/helpers/studios_helper.rb
# frozen_string_literal: true
module StudiosHelper
  def format_jpy(num)
    "¥ #{num.to_s.gsub(/(\d)(?=(\d{3})+(?!\d))/, '\1,')}"
  end

  def table_format(value)
    return '○' if value.is_a?(String)

    case value
    when Settings.status.none
      '×'
    when Settings.status.exist
      '○'
    when Settings.status.unknown
      '不明'
    end
  end

  def people_range_format(people_range_id)
    return '' if people_range_id.blank?
    PeopleRange.find(people_range_id).search_query_str
  end
end

app/views/admin/studios/_form.html.erb
<%= form_for [:admin, studio], class: 'form-horizontal' do |f| %>
  <% if studio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(studio.errors.count, "error") %> prohibited this studio from being saved:</h2>

      <ul>
      <% studio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'スタジオ名', class: 'control-label' %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'スタジオよも' %>
  </div>

  <div class="form-group">
    <%= f.label 'スタジオ名(URL表記)', class: 'control-label' %>
    <%= f.text_field :slug, class: 'form-control', placeholder: 'studio-yomo' %>
  </div>

  <div class="form-group">
    <%= f.label 'エリア', class: 'control-label' %>
    <%= f.select :area_id, Area.all.map{|a| [a.city, a.id]}, {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label '住所', class: 'control-label' %>
    <%= f.text_field :address, class: 'form-control', placeholder: '東京都目黒区上目黒1-18-11-604' %>
  </div>

  <div class="form-group">
    <%= f.label '最寄り駅1', class: 'control-label' %>
    <%= f.text_field :nearest_station_1, class: 'form-control', placeholder: '中目黒' %>
  </div>

  <div class="form-group">
    <%= f.label '最寄り駅2', class: 'control-label' %>
    <%= f.text_field :nearest_station_2, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label '最寄り駅3', class: 'control-label' %>
    <%= f.text_field :nearest_station_3, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label '電話番号', class: 'control-label' %>
    <%= f.text_field :tel, class: 'form-control', placeholder: '03-6883-9722' %>
  </div>

  <div class="form-group">
    <%= f.label '営業時間(開始)', class: 'control-label' %>
    <%= f.time_select :start_hours, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label '営業時間(終了)', class: 'control-label' %>
    <%= f.time_select :end_hours, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label '深夜レンタル', class: 'control-label' %>
    <%= f.select :late_night, [ [ '無', 0 ], [ '有', 1 ], [ '不明', 99 ]], class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label 'ロッカールーム', class: 'control-label' %>
    <%= f.select :locker_room, [ [ '無', 0 ], [ '有', 1 ], [ '不明', 99 ]], class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label '駐車場', class: 'control-label' %>
    <%= f.select :parking, [ [ '無', 0 ], [ '有', 1 ], [ '不明', 99 ]], class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label 'キャンセル期限', class: 'control-label' %>
    <%= f.text_field :cancell_deadline, class: 'form-control', placeholder: '前日50％ 当日100％' %>
  </div>

  <div class="form-group">
    <%= f.label 'スタジオHP', class: 'control-label' %>
    <%= f.text_field :url, class: 'form-control', placeholder: 'http://www.vintom.co.jp' %>
  </div>

  <div class="form-group">
    <%= f.label '特徴', class: 'control-label' %>
    <%= f.text_area :feature, class: 'form-control', placeholder: '日本最大のストリートダンサー専門プロダクションの運営、日本一の大学ダンスサークルを決めるJapan Dancers’ Championshipをはじめとしたイベント企画・制作、他社メディアとも提携したダンサープラットフォームを活かしたブランド認知支援・広告宣伝活動支援などダンスに関わる様々な事業を行っています。' %>
  </div>

  <div class="form-group">
    <%= f.label '備考', class: 'control-label' %>
    <%= f.text_area :remarks, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label 'ステータス', class: 'control-label' %>
    <%= f.select :status, Studio.statuses.keys.to_a, {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label '事務局メモ', class: 'control-label' %>
    <%= f.text_area :memo, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label 'キャプチャ', class: 'control-label' %>
    <%= f.fields_for :studio_images do |image| %>
      <%= image.file_field :url, class: 'filestyle', width: '50%' %>
    <% end %>
    <% @studio.studio_images.each do |i| %>
      <%= image_tag i.url, width: '16%', style: 'margin: 20px;text-align:right;'%>
    <% end %>
  </div>

  <div class="form-group">
    metaデータ
    <ul>
      <li>
        <%= f.label 'title', class: 'control-label' %>
        <%= f.text_area :meta_title, class: 'form-control' %>
      </li>
      <li>
        <%= f.label 'description', class: 'control-label' %>
        <%= f.text_area :meta_description, class: 'form-control' %>
      </li>
      <li>
        <%= f.label 'ogp_image', class: 'control-label' %>
        <%= f.text_area :meta_ogp_image_url, class: 'form-control' %>
      </li>
    </ul>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/studios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Studios</h1>

<%= link_to 'New Studio', new_admin_studio_path %>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>スタジオ名</th>
      <th>エリア</th>
      <th>住所</th>
      <th>最寄り駅</th>
      <th>電話番号</th>
      <th>営業時間</th>
      <th>状態</th>
      <th>メモ</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @studios.each do |studio| %>
      <tr>
        <td><%= studio.id %></td>
        <td><%= studio.name %></td>
        <td><%= studio.area.city %></td>
        <td><%= studio.address %></td>
        <td><%= "#{studio.nearest_station_1}, #{studio.nearest_station_2}, #{studio.nearest_station_3}" %></td>
        <td><%= studio.tel %></td>
        <td><%= "#{studio.start_hours&.strftime("%H:%M")} - #{studio.end_hours&.strftime("%H:%M")}" %></td>
        <td><%= studio.status %></td>
        <td><%= studio.memo %></td>
        <td><%= link_to 'Image edit', admin_studio_upload_path(studio) %></td>
        <td><%= link_to 'Edit', edit_admin_studio_path(studio) %></td>
        <td><%= link_to 'Destroy', admin_studio_path(studio), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @studios %>

<br>

<%= link_to 'New Studio', new_admin_studio_path %>

app/views/admin/studios/upload.html.erb
<h1>Studio Images Upload</h1>

<%= form_tag(upload_admin_studio_studio_images_path(@studio), id: 'studio-image-dropzone', class: 'dropzone', method: :post) %>

<script type="text/javascript">
  Dropzone.autoDiscover = false;

  Dropzone.options.studioImageDropzone = {
    paramName: "file",         // input fileの名前
    parallelUploads: 10,            // 1度に何ファイルずつアップロードするか
    acceptedFiles: 'image/*',   // 画像だけアップロードしたい場合
    maxFiles: 10,                      // 1度にアップロード出来るファイルの数
    maxFilesize: 100,                // 1つのファイルの最大サイズ(1=1M)
    dictFileTooBig: "ファイルが大きすぎます。 ({{filesize}}MiB). 最大サイズ: {{maxFilesize}}MiB.",
    dictInvalidFileType: "画像ファイル以外です。",
    dictMaxFilesExceeded: "一度にアップロード出来るのは10ファイルまでです。",
    dictDefaultMessage: 'アップロードする画像をここにドラッグ&ドロップしてください。'
  };
  var studioImageDropzone = new Dropzone("#studio-image-dropzone");
</script>