config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  resources :rooms
  resources :studios
  resources :studios do
    member do
      get 'studio_image'
    end
  end
  resources :accounts
  namespace :admin do
    root 'top#index'
    resources :studios do
      get :upload
      resources :studio_images do
        collection do
          post :upload
        end
      end
    end
    resources :rooms
    resources :areas
  end
  get '*unmatched_route', to: redirect('/'), format: false unless Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VStudio</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar-top-fix navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to '管理画面', admin_root_path, class: 'navbar-brand' %>
        </div>
    
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to 'スタジオ', admin_studios_path %></li>
            <li><%= link_to 'ルーム', admin_rooms_path %></li>
            <li><%= link_to 'エリア', admin_areas_path %></li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>レンタルダンススタジオ検索</title>
    <meta name="description"  content="目的にあったスペックのダンス用のレンタルスタジオは探すだけでも時間がかかって大変・・・。「レンタルダンススタジオ検索」はこんな不便を解消します。独自のレンタル用ダンススタジオのデータベースを使って練習に必要なスタジオをシンプルなUIで簡単に検索できます。"/>
    <link rel="shortcut icon" href="https://sagasu.space/images/vintom.png" type="image/png">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:title" content="レンタルダンススタジオ検索" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://sagasu.space/" />
    <meta property="og:image" content="https://sagasu.space/assets/top.jpg" />
    <meta property="og:site_name" content="レンタルダンススタジオ検索" />
    <meta property="og:description" content="目的にあったスペックのダンス用のレンタルスタジオは探すだけでも時間がかかって大変・・・。「レンタルダンススタジオ検索」はこんな不便を解消します。独自のレンタル用ダンススタジオのデータベースを使って練習に必要なスタジオをシンプルなUIで簡単に検索できます。" /> 
    <meta property="fb:app_id" content="1170194636409472">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render partial: 'shared/google_analytics' %>
  </head>

  <body>
    <nav class="navbar-fixed-top navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'レンタルダンススタジオ検索',root_path, class: 'navbar-brand'%>
        </div>
    
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
          <%= form_tag studios_path, class: "navbar-form navbar-right", role: "search", method: :get do %>
            <div class="form-group">
              <% if params[:area].present? %>
                <%= select '', :area, Area.all.map{ |a| [a.city, a.slug] }, {selected: params[:area]}, {class: 'form-control'} %>
              <% else %>
                <%= select '', :area, Area.all.map{ |a| [a.city, a.slug] }, {prompt: 'エリア'}, {class: 'form-control'} %>
              <% end %>
            </div>
            &nbsp;
            <div class="form-group">
              <% if params[:people].present? %>
                <%= select '', :people, PeopleRange.all.map{|p| [p.name, p.id]}, {selected: params[:people]}, {class: 'form-control'} %>
              <% else %>
                <%= select '', :people, PeopleRange.all.map{|p| [p.name, p.id]}, {prompt: '人数'}, {class: 'form-control'} %>
              <% end %>
            </div>
            &nbsp;
            <%= button_tag '探す', class: 'btn btn-info', type: :submit %>
          <% end %>
        </div>
      </div>
    </nav>
    <%= yield %>
    <a href="http://vintom.co.jp/" target='_blank'>
      <div class="l-footer-copyright col-sm-12">
        <%= image_tag('vintom_logo.png') %>
        <p><small>All Right Reserved. Vintom, Inc.</small></p>
      </div>
    </a>
  </body>
</html>

app/views/layouts/studio.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @studio.meta_title.presence || "#{@studio.name} | レンタルダンススタジオ検索" %></title>
    <meta name="description"  content="<%= @studio.meta_description.presence || "#{@studio.area.city}のレンタルスタジオ「#{@studio.name}」のページです。「#{@studio.name}」の広さ、料金、営業時間といった基本情報から更衣室や駐車場、wifiの有無まで様々な情報を掲載しています。" %>"/>
    <link rel="shortcut icon" href="https://sagasu.space/images/vintom.png" type="image/png">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:title" content="<%= @studio.meta_title.presence || "#{@studio.name} ｜ レンタルダンススタジオ検索" %>"/>
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= studio_url(@studio.id) %>" />
    <meta property="og:image" content="<%= @studio.meta_ogp_image_url || image_url(studio_image_studio_path(@studio)) %>" />
    <meta property="og:site_name" content="レンタルダンススタジオ検索" />
    <meta property="og:description" content="<%= @studio.meta_description.presence || "#{@studio.area.city}のレンタルスタジオ「#{@studio.name}」のページです。「#{@studio.name}」の広さ、料金、営業時間といった基本情報から更衣室や駐車場、wifiの有無まで様々な情報を掲載しています。" %>"/>
    <meta property="fb:app_id" content="1170194636409472">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render partial: 'shared/google_analytics' %>
  </head>

  <body>
    <nav class="navbar-fixed-top navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'レンタルダンススタジオ検索',root_path, class: 'navbar-brand'%>
        </div>
    
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
          <%= form_tag studios_path, class: "navbar-form navbar-right", role: "search", method: :get do %>
            <div class="form-group">
              <% if session[:area].present? && session[:area] != 'all' %>
                <%= select '', :area, grouped_options_for_select(Area.all.group_by(&:prefecture).each{|area| area[1].map! {|x| [x.city, x.slug]}}), {prompt: Area.find_by(slug: session[:area]).city}, {class: 'form-control'} %>
              <% else %>
                <%= select '', :area, grouped_options_for_select(Area.all.group_by(&:prefecture).each{|area| area[1].map! {|x| [x.city, x.slug]}}), {prompt: 'エリア'}, {class: 'form-control'} %>
              <% end %>
            </div>
            &nbsp;
            <div class="form-group">
              <% if session[:people].present? %>
                <%= select '', :people, PeopleRange.all.map{|p| [p.name, p.id]}, {selected: session[:people]}, {class: 'form-control'} %>
              <% else %>
                <%= select '', :people, PeopleRange.all.map{|p| [p.name, p.id]}, {prompt: '人数'}, {class: 'form-control'} %>
              <% end %>
            </div>
            &nbsp;
            <%= button_tag '探す', class: 'btn btn-info', type: :submit %>
          <% end %>
        </div>
      </div>
    </nav>
    <%= render '/shared/breadcrumb', crumbs: [
      { name: 'ホーム', path: root_path },
      { name: "#{@studio.area.city}", path: studios_path(area: @studio.area.slug, people: '')},
      { name: "#{@studio.name}", path: request.original_url}
    ] %>
    <%= yield %>
    <a href="http://vintom.co.jp/" target='_blank'>
      <div class="l-footer-copyright col-sm-12">
        <%= image_tag('vintom_logo.png') %>
        <p><small>All Right Reserved. Vintom, Inc.</small></p>
      </div>
    </a>
  </body>
</html>

app/views/layouts/studio_index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @area %>の<%= @people %>レンタルダンススタジオまとめ</title>
    <meta name="description"  content="<%= @area %>の<%= @people %>レンタル可能なダンススタジオをまとめました。「レンタルダンススタジオ検索」は更衣室の有無やwifi有無など、様々な条件であなたの目的にあったダンスの練習用貸しスタジオを検索できます。"/>
    <link rel="shortcut icon" href="https://sagasu.space/images/vintom.png" type="image/png">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:title" content="<%= @area %>の<%= @people %>レンタルダンススタジオまとめ" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://sagasu.space/" />
    <meta property="og:image" content="https://sagasu.space/assets/top.jpg" />
    <meta property="og:site_name" content="レンタルダンススタジオ検索" />
    <meta property="og:description" content="<%= @area %>の<%= @people %>レンタル可能なダンススタジオをまとめました。「レンタルダンススタジオ検索」は更衣室の有無やwifi有無など、様々な条件であなたの目的にあったダンスの練習用貸しスタジオを検索できます。"/>
    <meta property="fb:app_id" content="1170194636409472">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render partial: 'shared/google_analytics' %>
  </head>

  <body>
    <nav class="navbar-fixed-top navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'レンタルダンススタジオ検索',root_path, class: 'navbar-brand'%>
        </div>
    
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
          <%= form_tag studios_path, class: "navbar-form navbar-right", role: "search", method: :get do %>
            <div class="form-group">
              <% if session[:area] != 'all' %>
                <%= select '', :area, grouped_options_for_select(Area.all.group_by(&:prefecture).each{|area| area[1].map! {|x| [x.city, x.slug]}}), {prompt: Area.find_by(slug: session[:area]).city}, {class: 'form-control'} %>
              <% else %>
                <%= select '', :area, grouped_options_for_select(Area.all.group_by(&:prefecture).each{|area| area[1].map! {|x| [x.city, x.slug]}}), {prompt: 'エリア'}, {class: 'form-control'} %>
              <% end %>
            </div>
            &nbsp;
            <div class="form-group">
              <% if session[:people].present? %>
                <%= select '', :people, PeopleRange.all.map{|p| [p.name, p.id]}, {selected: session[:people]}, {class: 'form-control'} %>
              <% else %>
                <%= select '', :people, PeopleRange.all.map{|p| [p.name, p.id]}, {prompt: '人数'}, {class: 'form-control'} %>
              <% end %>
            </div>
            &nbsp;
            <%= button_tag '探す', class: 'btn btn-info', type: :submit %>
          <% end %>
        </div>
      </div>
    </nav>
    <%= yield %>
    <a href="http://vintom.co.jp/" target='_blank'>
      <div class="l-footer-copyright col-sm-12">
        <%= image_tag('vintom_logo.png') %>
        <p><small>All Right Reserved. Vintom, Inc.</small></p>
      </div>
    </a>
  </body>
</html>

app/views/layouts/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>首都圏スタジオ掲載数No.1｜レンタルダンススタジオ検索</title>
    <meta name="description"  content="目的にあったスペックのダンス用のレンタルスタジオは探すだけでも時間がかかって大変・・・。「レンタルダンススタジオ検索」はこんな不便を解消します。独自のレンタル用ダンススタジオのデータベースを使って練習に必要なスタジオをシンプルなUIで簡単に検索できます。"/>
    <link rel="shortcut icon" href="https://sagasu.space/images/vintom.png" type="image/png">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:title" content="レンタルダンススタジオ検索" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://sagasu.space/" />
    <meta property="og:image" content="https://sagasu.space/assets/top.jpg" />
    <meta property="og:site_name" content="レンタルダンススタジオ検索" />
    <meta property="og:description" content="目的にあったスペックのダンス用のレンタルスタジオは探すだけでも時間がかかって大変・・・。「レンタルダンススタジオ検索」はこんな不便を解消します。独自のレンタル用ダンススタジオのデータベースを使って練習に必要なスタジオをシンプルなUIで簡単に検索できます。" /> 
    <meta property="fb:app_id" content="1170194636409472">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'top', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render partial: 'shared/google_analytics' %>
  </head>

  <body style="background-color: #3E3F3A;">
    <nav class="navbar-fixed-top navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to 'レンタルダンススタジオ検索', root_path, class: 'navbar-brand' %>
        </div>
      </div>
    </nav>
    <%= yield %>
    <a href="http://vintom.co.jp/" target='_blank'>
      <div class="footer-copyright">
        <%= image_tag('vintom_logo.png') %>
        <p><small>All Right Reserved. Vintom, Inc.</small></p>
      </div>
    </a>
  </body>
</html>